# Pour les exercices

- Pour github regarder la [playlist](https://www.youtube.com/watch?v=_ZEWDGpM-vM&list=PLYCpMb24GpOC704uO9svUrihl-HY1tTJJ)
- Pour git regarder le [cours](https://missing.csail.mit.edu/2020/version-control/) 
- Utiliser des PR pour soumettre des solutions d'exercices et poser des questions.

# Séance aujourd'hui

## Exercice

En utilisant scikit-learn
- Récupérer les datasets iris, boston, digits.
- Tester les algorithmes classiques de classification/regression sur ces datasets. (régression linéaire, lasso, ridge regression, k-means, k-neighboors, régression logistique, bayesien naif)
- Penser à utiliser la méthodologie train_test_split.

In [11]:
import sklearn

In [12]:
sklearn.__version__

'0.19.1'

In [1]:
from sklearn.datasets import load_boston, load_digits, load_iris

In [13]:
from sklearn.linear_model import LinearRegression, Lasso, Ridge, LogisticRegression
from sklearn.neighbors import KNeighborsClassifier, KNeighborsRegressor
from sklearn.naive_bayes import GaussianNB

Pour la classification on voit qu'on pourra utiliser `LogisticRegression`, `KNeighboorsClassifier`, `GaussianNB`.

In [14]:
from sklearn.model_selection import train_test_split

# Iris dataset

In [2]:
iris = load_iris()

In [3]:
iris

{'data': array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
  

In [4]:
type(iris)

sklearn.utils.Bunch

In [5]:
dir(iris)

['DESCR', 'data', 'feature_names', 'target', 'target_names']

In [6]:
print(iris.DESCR)

Iris Plants Database

Notes
-----
Data Set Characteristics:
    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, predictive attributes and the class
    :Attribute Information:
        - sepal length in cm
        - sepal width in cm
        - petal length in cm
        - petal width in cm
        - class:
                - Iris-Setosa
                - Iris-Versicolour
                - Iris-Virginica
    :Summary Statistics:

    ============== ==== ==== ======= ===== ====================
                    Min  Max   Mean    SD   Class Correlation
    ============== ==== ==== ======= ===== ====================
    sepal length:   4.3  7.9   5.84   0.83    0.7826
    sepal width:    2.0  4.4   3.05   0.43   -0.4194
    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)
    petal width:    0.1  2.5   1.20  0.76     0.9565  (high!)
    ============== ==== ==== ======= ===== ====================

    :Missing Attribute Values: None
  

In [7]:
X, y = iris.data, iris.target

In [9]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [10]:
iris.target_names

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [15]:
X_tr, X_te, y_tr, y_te = train_test_split(X, y)

In [17]:
logreg = LogisticRegression()
nb = GaussianNB()
kne = KNeighborsClassifier()  # Ajuster l'hyperparamètre nombre de voisins

In [18]:
logreg.fit(X_tr, y_tr)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [19]:
nb.fit(X_tr, y_tr)

GaussianNB(priors=None)

In [20]:
kne.fit(X_tr, y_tr)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=5, p=2,
           weights='uniform')

## Evaluer les performances des différents modèles

In [21]:
dir(logreg)

['C',
 '__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__setstate__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_estimator_type',
 '_get_param_names',
 '_predict_proba_lr',
 'class_weight',
 'classes_',
 'coef_',
 'decision_function',
 'densify',
 'dual',
 'fit',
 'fit_intercept',
 'get_params',
 'intercept_',
 'intercept_scaling',
 'max_iter',
 'multi_class',
 'n_iter_',
 'n_jobs',
 'penalty',
 'predict',
 'predict_log_proba',
 'predict_proba',
 'random_state',
 'score',
 'set_params',
 'solver',
 'sparsify',
 'tol',
 'verbose',
 'warm_start']

In [22]:
logreg.score(X_te, y_te)

0.9473684210526315

In [23]:
nb.score(X_te, y_te)

0.9210526315789473

In [24]:
kne.score(X_te, y_te)

0.9210526315789473

## Regarder comment récupérer la matrice de confusion.

In [25]:
from sklearn.metrics import confusion_matrix

In [26]:
confusion_matrix(y_te, logreg.predict(X_te))

array([[10,  0,  0],
       [ 0, 13,  2],
       [ 0,  0, 13]], dtype=int64)

In [27]:
confusion_matrix(y_te, nb.predict(X_te))

array([[10,  0,  0],
       [ 0, 13,  2],
       [ 0,  1, 12]], dtype=int64)

In [28]:
confusion_matrix(y_te, kne.predict(X_te))

array([[10,  0,  0],
       [ 0, 12,  3],
       [ 0,  0, 13]], dtype=int64)

## A quoi correspond le score?

In [31]:
(10 + 13 + 13) / (10 + 0 + 0 + 0 + 13 + 2 + 0 + 0 + 13)

0.9473684210526315

In [32]:
(10 + 13 + 12) / (10 + 0 + 0 + 0 + 13 + 2 + 0 + 1 + 12)

0.9210526315789473

In [33]:
(10 + 12 + 13) / (10 + 0 + 0 + 0 + 12 + 3 + 0 + 0 + 13)

0.9210526315789473

## ATTENTION

En fait même si le calcul revient au même le score était la moyenne pondérée des précisions.

## Faire la crossvalidation à 3 morceaux à la main 
juste avec `train_test_split`, et en ajoutant les modèles kne à 3 et 7 voisins.

In [38]:
X_intermed, X_3, y_intermed, y_3 = train_test_split(X_tr, y_tr, test_size=0.33)
X_1, X_2, y_1, y_2 = train_test_split(X_intermed, y_intermed, test_size=0.5)
mon_decoupage = ((X_1, y_1), (X_2, y_2), (X_3, y_3))

In [35]:
logreg = LogisticRegression()
nb = GaussianNB()
kne3 = KNeighborsClassifier(n_neighbors=3)
kne5 = KNeighborsClassifier(n_neighbors=5)
kne7 = KNeighborsClassifier(n_neighbors=7)

In [39]:
import numpy as np

In [41]:
print(X_1.shape, X_2.shape, np.concatenate((X_1, X_2), axis=0).shape)

(37, 4) (38, 4) (75, 4)


In [42]:
def moyenne(genere_modele):
    resultat = 0
    X_tr = np.concatenate((X_1, X_2), axis=0)
    y_tr = np.concatenate((y_1, y_2), axis=0)
    modele = genere_modele()
    modele.fit(X_tr, y_tr)
    resultat += modele.score(X_3, y_3)
    X_tr = np.concatenate((X_3, X_2), axis=0)
    y_tr = np.concatenate((y_3, y_2), axis=0)
    modele = genere_modele()
    modele.fit(X_tr, y_tr)
    resultat += modele.score(X_1, y_1)
    X_tr = np.concatenate((X_1, X_3), axis=0)
    y_tr = np.concatenate((y_1, y_3), axis=0)
    modele = genere_modele()
    modele.fit(X_tr, y_tr)
    resultat += modele.score(X_2, y_2)
    return resultat / 3

In [43]:
moyenne(LogisticRegression)

0.8828828828828829

In [44]:
moyenne(GaussianNB)

0.9642010431484116

In [45]:
moyenne(lambda :KNeighborsClassifier(n_neighbors=3))

0.9729729729729729

In [46]:
moyenne(lambda :KNeighborsClassifier(n_neighbors=5))

0.981981981981982

In [47]:
moyenne(lambda :KNeighborsClassifier(n_neighbors=7))

0.9729729729729729

In [48]:
modele_choisi = KNeighborsClassifier(n_neighbors=5)

In [49]:
modele_choisi.fit(X_tr, y_tr)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=5, p=2,
           weights='uniform')

In [50]:
modele_choisi.score(X_tr, y_tr)

0.9910714285714286

In [51]:
modele_choisi.score(X_te, y_te)

0.9210526315789473

# Exercice

- Nettoyer et généraliser la procédure précédente.
- Etendre aux autres jeux de données.
- Regarder le moyen de faire "automatiquement" la cross validation via scikit-learn.